#!/usr/bin/env python3
"""Convert an image (default: xyh.jpg) to RGB565 C source for the ST7789 320x240
display on STM32H743.

Pipeline:
  1. Open image, composite transparency on black if needed.
  2. Center-crop to the 4:3 target aspect, then resize to 320x240 (LANCZOS).
     Use --fit to scale-to-fit instead (black bars, no cropping).
  3. Convert to RGB565, bytes emitted MSB-first (the byte order ST7789
     expects when streaming pixel data after the RAMWR (0x2C) command).
  4. Write Inc/xyh_image.h and Src/xyh_image.c, plus a preview PNG.

Usage:
  python tools/convert_image.py [--input PATH] [--fit] [--out-name NAME]
"""
import argparse
import os
import sys

from PIL import Image

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
W, H = 320, 240


def rgb565_pixels(im):
    """Yield the RGB565 value (int) for each pixel in row-major order."""
    px = im.load()
    for y in range(H):
        for x in range(W):
            r, g, b = px[x, y]
            yield ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def center_crop(im):
    """Crop to the 4:3 target aspect, keeping the center, no upscaling."""
    sw, sh = im.size
    target_aspect = W / H
    src_aspect = sw / sh
    if src_aspect > target_aspect:
        # too wide: crop the sides
        cw = int(round(sh * target_aspect))
        left = (sw - cw) // 2
        return im.crop((left, 0, left + cw, sh))
    else:
        # too tall: crop top/bottom
        ch = int(round(sw / target_aspect))
        top = (sh - ch) // 2
        return im.crop((0, top, sw, top + ch))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", default=os.path.join(PROJECT_ROOT, "xyh.jpg"))
    ap.add_argument("--fit", action="store_true",
                    help="scale to fit instead of center-crop (black bars)")
    ap.add_argument("--out-name", default="xyh_image")
    args = ap.parse_args()

    im = Image.open(args.input)
    print(f"Source: {args.input} {im.size} {im.mode}")

    if im.mode in ("RGBA", "LA", "P"):
        im = im.convert("RGBA")
        bg = Image.new("RGB", im.size, (0, 0, 0))
        bg.paste(im, mask=im.split()[3])
        im = bg
    else:
        im = im.convert("RGB")

    if args.fit:
        # scale to fit: height fills 240, width centered with black bars
        scale = min(W / im.width, H / im.height)
        nw, nh = int(round(im.width * scale)), int(round(im.height * scale))
        im = im.resize((nw, nh), Image.LANCZOS)
        canvas = Image.new("RGB", (W, H), (0, 0, 0))
        canvas.paste(im, ((W - nw) // 2, (H - nh) // 2))
        im = canvas
    else:
        im = center_crop(im).resize((W, H), Image.LANCZOS)

    # preview
    preview_dir = os.path.join(PROJECT_ROOT, "tools", "preview")
    os.makedirs(preview_dir, exist_ok=True)
    preview_path = os.path.join(preview_dir, f"{args.out_name}_320x240.png")
    im.save(preview_path)
    print(f"Preview: {preview_path}")

    # RGB565 bytes, MSB first
    data = bytearray(W * H * 2)
    i = 0
    for v in rgb565_pixels(im):
        data[i] = (v >> 8) & 0xFF
        data[i + 1] = v & 0xFF
        i += 2

    name = args.out_name
    inc_dir = os.path.join(PROJECT_ROOT, "Inc")
    src_dir = os.path.join(PROJECT_ROOT, "Src")
    os.makedirs(inc_dir, exist_ok=True)
    os.makedirs(src_dir, exist_ok=True)

    hdr = f"""/**
 * @file {name}.h
 * @brief RGB565 pixel data for the ST7789 320x240 display.
 *        Generated by tools/convert_image.py -- do not edit by hand.
 *        Bytes are MSB-first, row-major: exactly what the ST7789 RAMWR
 *        (0x2C) command expects with COLMOD = 0x55 (16 bpp).
 */
#ifndef {name.upper()}_H
#define {name.upper()}_H

#include <stdint.h>

#define {name.upper()}_WIDTH    {W}U
#define {name.upper()}_HEIGHT   {H}U
#define {name.upper()}_SIZE     ({name.upper()}_WIDTH * {name.upper()}_HEIGHT * 2U)

extern const uint8_t {name}[{name.upper()}_SIZE];

#endif /* {name.upper()}_H */
"""
    with open(os.path.join(inc_dir, f"{name}.h"), "w", encoding="utf-8") as f:
        f.write(hdr)

    n = len(data)
    with open(os.path.join(src_dir, f"{name}.c"), "w", encoding="utf-8") as f:
        f.write(f'#include "{name}.h"\n\n')
        f.write(f"const uint8_t {name}[{name.upper()}_SIZE] = {{\n")
        for off in range(0, n, 16):
            row = ", ".join(f"0x{b:02X}" for b in data[off:off + 16])
            f.write(f"    {row},\n")
        f.write("};\n")

    print(f"Wrote Inc/{name}.h and Src/{name}.c ({n} bytes RGB565, "
          f"{n / 1024:.1f} KiB)")


if __name__ == "__main__":
    main()
